"use client"

import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react"
import { Download, Loader2, Network, Upload, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useTranslations } from "@/hooks/use-translations"
import { useObjectUrl } from "@/hooks/use-object-url"
import { createHarSample, createHarSession } from "@/lib/har-client"
import { HAR_PHASES, HarError, harDisplayUrl, harSummary, type HarData, type HarDetail, type HarPair, type HarRow } from "@/lib/har-shared"

const frame = "rounded-2xl border border-md-outline-variant bg-md-surface-container-lowest p-4 sm:p-5"
const selectClass = "h-10 w-full rounded-lg border border-md-outline-variant bg-md-surface px-3 text-sm"
const colors = { blocked: "#94a3b8", dns: "#3b82f6", connect: "#8b5cf6", send: "#06b6d4", wait: "#f59e0b", receive: "#22c55e" }
const ms = (value: number | null) => value === null ? "—" : `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })} ms`
const size = (value: number | null) => value === null ? "—" : value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(2)} MB`

export default function HarPanel() {
  const t = useTranslations("harTools")
  const [file, setFile] = useState<File | null>(null), [data, setData] = useState<HarData | null>(null), [phase, setPhase] = useState<"load" | "export" | null>(null), [notice, setNotice] = useState("")
  const [search, setSearch] = useState(""), [host, setHost] = useState("all"), [pageFilter, setPageFilter] = useState("all"), [kind, setKind] = useState("all"), [method, setMethod] = useState("all"), [slow, setSlow] = useState(1000)
  const [sort, setSort] = useState<"start" | "duration" | "transfer" | "status">("start"), [descending, setDescending] = useState(false), [page, setPage] = useState(0), [reveal, setReveal] = useState(false)
  const [selected, setSelected] = useState<number | null>(null), [detail, setDetail] = useState<HarDetail | null>(null), [detailBusy, setDetailBusy] = useState(false), [output, setOutput] = useState<File | null>(null)
  const input = useRef<HTMLInputElement>(null), session = useRef<ReturnType<typeof createHarSession> | null>(null), version = useRef(0), detailVersion = useRef(0)
  const outputUrl = useObjectUrl(output), query = useDeferredValue(search).trim().toLowerCase(), busy = phase !== null, filtering = query !== search.trim().toLowerCase()
  const base = useMemo(() => (data?.rows ?? []).filter(row => (host === "all" || `host:${row.host}` === host) && (pageFilter === "all" || `page:${row.page}` === pageFilter) && (method === "all" || row.method === method) && (!query || `${row.method} ${row.url} ${row.status ?? ""} ${row.mime}`.toLowerCase().includes(query))), [data, host, pageFilter, method, query])
  const rows = useMemo(() => base.filter(row => kind === "all" || kind === "failed" && row.failed || kind === "slow" && row.duration !== null && row.duration >= slow || kind === "repeated" && row.repeats > 1).sort((a, b) => { const av = a[sort], bv = b[sort]; return av === null ? bv === null ? a.id - b.id : 1 : bv === null ? -1 : (av - bv) * (descending ? -1 : 1) || a.id - b.id }), [base, kind, slow, sort, descending])
  const summary = useMemo(() => harSummary(rows, slow), [rows, slow]), baseSummary = useMemo(() => harSummary(base, slow), [base, slow])
  const pageCount = Math.max(1, Math.ceil(rows.length / 100)), currentPage = Math.min(page, pageCount - 1), visible = rows.slice(currentPage * 100, (currentPage + 1) * 100)
  const selectedRow = data?.rows.find(row => row.id === selected)
  const hosts = useMemo(() => [...new Set(data?.rows.map(row => row.host) ?? [])].sort(), [data]), methods = useMemo(() => [...new Set(data?.rows.map(row => row.method) ?? [])].sort(), [data]), pages = useMemo(() => [...new Set(data?.rows.map(row => row.page) ?? [])], [data])
  const currentPageInfo = data?.pages.find(value => `page:${value.id}` === pageFilter)
  useEffect(() => () => { version.current++; detailVersion.current++; session.current?.dispose() }, [])
  useEffect(() => {
    let ignore = false; const ticket = ++detailVersion.current
    setDetail(null)
    if (selected === null || !session.current) { setDetailBusy(false); return }
    setDetailBusy(true)
    void session.current.run({ action: "detail", id: selected, reveal }).then(response => { if (!ignore && ticket === detailVersion.current && "detail" in response) setDetail(response.detail) }).catch(error => { if (!ignore && ticket === detailVersion.current && (!(error instanceof HarError) || error.code !== "cancelled")) setNotice(`error_${error instanceof HarError ? error.code : "engine"}`) }).finally(() => { if (!ignore && ticket === detailVersion.current) setDetailBusy(false) })
    return () => { ignore = true }
  }, [selected, reveal])
  const clear = () => { version.current++; detailVersion.current++; session.current?.dispose(); session.current = null; setFile(null); setData(null); setSelected(null); setDetail(null); setPhase(null); setOutput(null); setNotice(""); setDetailBusy(false); setReveal(false) }
  const resetView = () => { setPage(0); setSelected(null); setDetail(null); setOutput(null) }
  const load = async (incoming: File) => {
    clear(); setFile(incoming); setPhase("load"); const ticket = ++version.current
    try { const current = createHarSession(); session.current = current; const response = await current.run({ action: "load", file: incoming }); if (ticket === version.current && "data" in response) { setData(response.data); setSearch(""); setHost("all"); setPageFilter("all"); setMethod("all"); setKind("all"); setPage(0); setSort("start"); setDescending(false) } }
    catch (error) { if (ticket === version.current) { session.current?.dispose(); session.current = null; setNotice(`error_${error instanceof HarError ? error.code : "engine"}`) } }
    finally { if (ticket === version.current) setPhase(null) }
  }
  const exportRows = async (format: "csv" | "json") => {
    if (!session.current || busy || detailBusy || filtering || !rows.length) return
    const ticket = ++version.current; setOutput(null); setPhase("export"); setNotice("")
    try { const response = await session.current.run({ action: "export", ids: rows.map(row => row.id), format, reveal }); if (ticket === version.current && "output" in response) setOutput(new File([response.output], `network-summary.${format}`, { type: response.output.type })) }
    catch (error) { if (ticket === version.current) setNotice(`error_${error instanceof HarError ? error.code : "engine"}`) }
    finally { if (ticket === version.current) setPhase(null) }
  }
  const timingBar = (row: HarRow) => {
    if (row.start === null || row.duration === null || summary.start === null || summary.span === null) return <span className="text-xs text-md-on-surface-variant">{t("unknown")}</span>
    const span = Math.max(1, summary.span), left = Math.min(99.5, Math.max(0, (row.start - summary.start) / span * 100)), width = Math.min(100 - left, Math.max(0.5, row.duration / span * 100)), sum = HAR_PHASES.reduce((value, key) => value + (row.timings[key] ?? 0), 0)
    return <div className="relative h-4 w-56 rounded bg-md-surface-container" title={`${t("startOffset")} ${ms(row.start - summary.start)} · ${ms(row.duration)}`}><div className="absolute inset-y-0 flex overflow-hidden rounded bg-slate-400" style={{ left: `${left}%`, width: `${width}%` }}>{HAR_PHASES.map(key => <span key={key} style={{ background: colors[key], width: `${(row.timings[key] ?? 0) / Math.max(1, sum, row.duration!) * 100}%` }} title={`${t(`timing_${key}`)} ${ms(row.timings[key])}`} />)}</div></div>
  }
  const pairsView = (title: string, pairs: HarPair[]) => <section className="min-w-0 space-y-2"><h3 className="text-sm font-semibold">{title}</h3>{pairs.length ? <dl className="max-h-64 overflow-auto rounded-lg border border-md-outline-variant p-3 text-xs">{pairs.map((pair, index) => <div key={index} className="grid gap-1 border-b border-md-outline-variant py-2 last:border-0 sm:grid-cols-[minmax(100px,1fr)_2fr]"><dt className="break-all font-medium">{pair.name}</dt><dd className="whitespace-pre-wrap break-all font-mono">{pair.value}</dd></div>)}</dl> : <p className="text-xs text-md-on-surface-variant">{t("notRecorded")}</p>}</section>
  return <div className="space-y-5">
    <header><h1 className="flex items-center gap-3 text-2xl font-semibold"><Network className="h-7 w-7 text-md-primary" />{t("title")}</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-md-on-surface-variant">{t("description")}</p></header>
    <section className={`${frame} space-y-3`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if (event.dataTransfer.files[0]) void load(event.dataTransfer.files[0]) }}>
      <input ref={input} aria-label={t("upload")} type="file" accept=".har,.json,application/json" className="hidden" onChange={event => { if (event.target.files?.[0]) void load(event.target.files[0]); event.target.value = "" }} />
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => input.current?.click()}><Upload />{t("upload")}</Button><Button variant="ghost" onClick={() => void load(createHarSample())}>{t("sample")}</Button>{file && <Button variant="ghost" onClick={clear}><X />{t("clear")}</Button>}</div>
      <p className="text-xs leading-5 text-md-on-surface-variant">{t("limits")} {t("localHint")}</p>{file && <p className="break-all text-sm">{file.name} · {size(file.size)}{data?.creator ? ` · ${data.creator}` : ""}{data?.version ? ` · HAR ${data.version}` : ""}</p>}
      {busy && <div role="status" className="flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin" />{t(`phase_${phase}`)}<Button size="sm" variant="outline" onClick={clear}>{t("cancel")}</Button></div>}{notice && <p role="alert" className="text-sm text-md-error">{t(notice)}</p>}{data && data.skipped > 0 && <p role="status" className="text-sm text-md-on-surface-variant">{t("skipped").replace("{count}", String(data.skipped))}</p>}
    </section>
    {data && <>
      <section className={`${frame} space-y-4`}>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="space-y-1 text-sm sm:col-span-2"><span>{t("search")}</span><Input aria-label={t("search")} value={search} disabled={busy} onChange={event => { setSearch(event.target.value); resetView() }} placeholder={t("searchHint")} /></label><label className="space-y-1 text-sm"><span>{t("host")}</span><select aria-label={t("host")} className={selectClass} value={host} disabled={busy} onChange={event => { setHost(event.target.value); resetView() }}><option value="all">{t("allHosts")}</option>{hosts.map(value => <option key={value} value={`host:${value}`}>{value || t("noHost")}</option>)}</select></label><label className="space-y-1 text-sm"><span>{t("page")}</span><select aria-label={t("page")} className={selectClass} value={pageFilter} disabled={busy} onChange={event => { setPageFilter(event.target.value); resetView() }}><option value="all">{t("allPages")}</option>{pages.map(value => <option key={value} value={`page:${value}`}>{data.pages.find(item => item.id === value)?.title || value || t("noPage")}</option>)}</select></label></div>
        <div className="flex flex-wrap items-end gap-3"><label className="w-32 space-y-1 text-sm"><span>{t("method")}</span><select aria-label={t("method")} className={selectClass} value={method} disabled={busy} onChange={event => { setMethod(event.target.value); resetView() }}><option value="all">{t("allMethods")}</option>{methods.map(value => <option key={value}>{value}</option>)}</select></label><label className="w-40 space-y-1 text-sm"><span>{t("slowThreshold")}</span><Input aria-label={t("slowThreshold")} type="number" min={0} max={86400000} step={100} value={slow} disabled={busy} onChange={event => { const value = Number(event.target.value); if (Number.isFinite(value)) setSlow(Math.max(0, Math.min(86400000, value))); resetView() }} /></label><label className="w-40 space-y-1 text-sm"><span>{t("sort")}</span><select aria-label={t("sort")} className={selectClass} value={sort} disabled={busy} onChange={event => { setSort(event.target.value as typeof sort); resetView() }}>{["start", "duration", "transfer", "status"].map(key => <option key={key} value={key}>{t(key)}</option>)}</select></label><Button variant="outline" disabled={busy} onClick={() => { setDescending(!descending); resetView() }}>{t(descending ? "descending" : "ascending")}</Button></div>
        <div className="flex flex-wrap gap-2">{[["all", base.length], ["slow", baseSummary.slow], ["failed", baseSummary.failed], ["repeated", base.filter(row => row.repeats > 1).length]].map(([key, count]) => <Button key={key} size="sm" variant={kind === key ? "default" : "outline"} aria-pressed={kind === key} disabled={busy} onClick={() => { setKind(String(key)); resetView() }}>{t(`filter_${key}`)} ({count})</Button>)}</div>
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={reveal} disabled={busy} onChange={event => { setReveal(event.target.checked); setDetail(null); setOutput(null) }} />{t("reveal")}</label><p className="text-xs leading-5 text-md-on-surface-variant">{t("privacyHint")}</p>
        {currentPageInfo && <p className="text-xs text-md-on-surface-variant">{t("contentLoad")} {ms(currentPageInfo.contentLoad)} · {t("pageLoad")} {ms(currentPageInfo.load)}</p>}
      </section>
      <section className={`${frame} space-y-4`}>
        <h2 className="font-semibold">{t("summary")}</h2>{filtering && <p role="status" className="text-xs text-md-on-surface-variant">{t("filtering")}</p>}<div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["requests", String(summary.requests)], ["median", ms(summary.median)], ["p95", ms(summary.p95)], ["transferKnown", size(summary.transfer)]].map(([key, value]) => <div key={key} className="rounded-xl bg-md-surface-container-low p-3"><p className="text-xs text-md-on-surface-variant">{t(key)}</p><p className="mt-1 break-words font-semibold tabular-nums">{value}</p></div>)}</div>
        <p className="text-xs leading-5 text-md-on-surface-variant">{t("summaryHint").replace("{timed}", String(summary.timed)).replace("{unknown}", String(summary.transferUnknown))} {t("span")} {ms(summary.span)} · {t("repeats").replace("{groups}", String(summary.repeatedGroups)).replace("{extra}", String(summary.extraRequests))}</p>
        <p className="text-xs leading-5 text-md-on-surface-variant">{t("duplicateHint")}</p>
        <div className="flex flex-wrap gap-x-4 gap-y-2">{HAR_PHASES.map(key => <span key={key} className="flex items-center gap-1.5 text-xs"><span className="h-2.5 w-2.5 rounded-sm" style={{ background: colors[key] }} />{t(`timing_${key}`)}</span>)}</div>
        <div className="max-h-[680px] overflow-auto rounded-xl border border-md-outline-variant"><table className="w-full text-left text-xs"><thead className="sticky top-0 z-10 bg-md-surface-container"><tr>{["index", "request", "status", "duration", "transfer", "waterfall"].map(key => <th key={key} className="whitespace-nowrap px-3 py-3 font-semibold">{t(key)}</th>)}</tr></thead><tbody>{visible.map(row => <tr key={row.id} className={`border-t border-md-outline-variant ${row.id === selected ? "bg-md-secondary-container" : ""}`}><td className="px-3 py-3 tabular-nums">{row.id + 1}</td><td className="px-3 py-2"><button type="button" aria-label={`${t("viewRequest")} ${row.id + 1}`} disabled={busy || filtering} onClick={() => setSelected(row.id)} className="block w-80 max-w-md rounded text-left outline-offset-4 focus-visible:outline focus-visible:outline-2 focus-visible:outline-md-primary"><span className="font-semibold">{row.method}</span> <span className="text-md-on-surface-variant">{row.mime || t("unknown")}{row.repeats > 1 ? ` · ×${row.repeats}` : ""}</span><span className="mt-1 block truncate font-mono text-md-primary" title={harDisplayUrl(row.url, reveal)}>{harDisplayUrl(row.url, reveal)}</span></button></td><td className={`px-3 py-3 tabular-nums ${row.failed ? "text-md-error" : ""}`}>{row.status ?? "—"}{row.error ? " !" : ""}</td><td className="whitespace-nowrap px-3 py-3 tabular-nums">{ms(row.duration)}</td><td className="whitespace-nowrap px-3 py-3 tabular-nums">{size(row.transfer)}</td><td className="px-3 py-3">{timingBar(row)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-center text-sm text-md-on-surface-variant">{t("empty")}</p>}</div>
        <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-md-on-surface-variant">{t("pagination").replace("{page}", String(currentPage + 1)).replace("{pages}", String(pageCount)).replace("{count}", String(rows.length))}</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={currentPage === 0 || busy} onClick={() => setPage(currentPage - 1)}>{t("previous")}</Button><Button variant="outline" size="sm" disabled={currentPage >= pageCount - 1 || busy} onClick={() => setPage(currentPage + 1)}>{t("next")}</Button></div></div>
        <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || detailBusy || filtering || !rows.length} onClick={() => void exportRows("csv")}>{t("exportCsv")}</Button><Button variant="outline" disabled={busy || detailBusy || filtering || !rows.length} onClick={() => void exportRows("json")}>{t("exportJson")}</Button>{output && outputUrl && <Button asChild><a href={outputUrl} download={output.name}><Download />{t("download")} {output.name.split(".").at(-1)?.toUpperCase()}</a></Button>}</div>
      </section>
      {selectedRow && <section className={`${frame} space-y-4`}>
        <div className="flex justify-between gap-3"><h2 className="font-semibold">{t("detail")} #{selectedRow.id + 1}</h2><Button variant="ghost" size="sm" onClick={() => { setSelected(null); setDetail(null) }}>{t("close")}</Button></div>
        <p className="break-all font-mono text-sm">{selectedRow.method} {harDisplayUrl(selectedRow.url, reveal)}</p>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["status", `${selectedRow.status ?? "—"} ${selectedRow.statusText}`], ["duration", ms(selectedRow.duration)], ["bodySize", size(selectedRow.body)], ["contentSize", size(selectedRow.content)]].map(([key, value]) => <div key={key} className="text-sm"><p className="text-xs text-md-on-surface-variant">{t(key)}</p><p className="mt-1 break-words">{value}</p></div>)}</div>
        {selectedRow.error && <p className="break-all font-mono text-sm text-md-error">{selectedRow.error}</p>}
        <div className="flex flex-wrap gap-4">{[...HAR_PHASES, "ssl" as const].map(key => <p key={key} className="text-xs"><span className="text-md-on-surface-variant">{t(`timing_${key}`)}</span> {ms(selectedRow.timings[key])}</p>)}</div><p className="text-xs leading-5 text-md-on-surface-variant">{t("timingHint")}{selectedRow.timingMismatch ? ` ${t("timingMismatch")}` : ""}</p>
        {detailBusy && <p role="status" className="flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin" />{t("loadingDetail")}</p>}
        {detail && <><p className="text-xs text-md-on-surface-variant">IP: {detail.ip || "—"} · {t("connection")}: {detail.connection || "—"}</p><div className="grid gap-4 lg:grid-cols-2">{pairsView(t("requestHeaders"), detail.requestHeaders)}{pairsView(t("responseHeaders"), detail.responseHeaders)}{pairsView(t("query"), detail.query)}</div>{detail.headersTruncated && <p className="text-xs text-md-on-surface-variant">{t("pairsTruncated")}</p>}<div className="grid gap-4 lg:grid-cols-2">{(["request", "response"] as const).map(side => { const body = side === "request" ? detail.requestBody : detail.responseBody, length = side === "request" ? detail.requestLength : detail.responseLength; return <section key={side} className="min-w-0 space-y-2"><h3 className="text-sm font-semibold">{t(`${side}Body`)}{side === "response" && detail.encoding ? ` (${detail.encoding})` : ""}</h3><p className="text-xs text-md-on-surface-variant">{length === 0 ? t("notRecorded") : !reveal ? t("bodyHidden") : t("bodyCount").replace("{shown}", String(body.length)).replace("{total}", String(length))}</p>{reveal && body && <pre className="max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-lg border border-md-outline-variant p-3 font-mono text-xs">{body}</pre>}</section> })}</div></>}
      </section>}
    </>}
  </div>
}
